on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install Depedencies
        run: npm install

      - name: Build App
        run: npm run build
        env:
          CI: false

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: 103.176.79.132
          username: karyakami
          password: KaryaKami2022
          port: 22
          source: "build"
          target: "/var/www/batch3/dev/prod/rentalkuy"
          strip_components: 1
